# Generated by Django 5.1.3 on 2024-12-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WithoutChunks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='audio_size',
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error'), ('timeout', 'Timeout')], max_length=50),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='uuid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
